services:

  db:
    container_name: library_db
    image: postgres
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: library_app
    env_file: ./.env
    command: /app/run_app.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

#  nginx:
#    build: ./nginx
#    container_name: library_nginx
#    restart: always
#    env_file: ./.env
#    volumes:
#      - ./app/static_root:/app/static_root
#      - ./app/media:/app/media
#      - ./nginx/logs:/var/log/nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - app


volumes:
  db_data: